### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by cboden** [reactphp/ExampleChatWithRandomStranger#4]
Given a request I just received from GitHub on behalf of the owner of the "CHATROULETTE" trademark we've been advised to rename this repo within 1 week. 

Suggestions welcome. Off the top of my head, some proposals:
* TalkingSpinningWheel
* RandomJab
* OddConverse

@clue, @igorw, @jsor, @WyriHaximus

**Comment by WyriHaximus** [comment]
My favourite is `TalkingSpinningWheel` :+1: .

**Comment by clue** [comment]
I have no preference here and I'm good with either name :+1: 

I agree that it makes sense to rename this as is is not affiliated in any way with the "official chatroulette", but only shares its basic idea (conceptual, not technical or legal).

We should probably emphasize that this is not an application-quality project but more like a demo-project so I would actually tend towards a more technical name so people understand what this is all about (à la `ExampleChatWithRandomStranger` or `TalkingWithStrangers`).

**Comment by jeroenvdgulik** [comment]
I propose `NotTheRealChatRoulette`

**Comment by cboden** [comment]
Given the threat was rename the project or the reactphp organization will be removed from GitHub, I'd like to not poke the bear.  :)

**Comment by WyriHaximus** [comment]
Giving the treat `ExampleChatWithRandomStranger` might just be our safest option.
